<?php

namespace App\Console\Commands;

use App\Models\Report;
use App\Models\ReportPermission;
use Illuminate\Console\Command;

class SeedReports extends Command
{
    protected $signature = 'app:seed-reports';
    protected $description = 'Seed initial reports into the database';

    public function handle()
    {
        $this->info('Seeding reports...');

        $reports = [
            // SALES REPORTS
            [
                'name' => 'Revenue Over Time',
                'slug' => 'revenue-over-time',
                'description' => 'Track revenue trends over selected period',
                'category' => 'Sales',
                'type' => 'line_chart',
                'available_filters' => ['date_range' => ['today', 'yesterday', 'last_7_days', 'last_30_days', 'last_90_days', 'this_month', 'last_month', 'this_year', 'custom']],
                'default_date_range' => ['period' => 'last_30_days'],
                'display_order' => 1,
            ],
            [
                'name' => 'Revenue by Package',
                'slug' => 'revenue-by-package',
                'description' => 'Revenue breakdown by package',
                'category' => 'Sales',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'last_month', 'this_year', 'custom']],
                'display_order' => 2,
            ],
            [
                'name' => 'Revenue by affiliate',
                'slug' => 'revenue-by-affiliate',
                'description' => 'Track revenue generated by each affiliate',
                'category' => 'Sales',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year', 'custom']],
                'display_order' => 3,
            ],
            [
                'name' => 'Revenue by Payment Method',
                'slug' => 'revenue-by-payment-method',
                'description' => 'Payment method breakdown',
                'category' => 'Sales',
                'type' => 'pie_chart',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days']],
                'display_order' => 4,
            ],
            [
                'name' => 'Refund Analysis',
                'slug' => 'refund-analysis',
                'description' => 'Analyze refunds and cancellations',
                'category' => 'Sales',
                'type' => 'metric',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 5,
            ],
            [
                'name' => 'Promo Code Effectiveness',
                'slug' => 'promo-code-effectiveness',
                'description' => 'Track promo code usage and effectiveness',
                'category' => 'Sales',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 6,
            ],

            // ORDER REPORTS
            [
                'name' => 'Orders Over Time',
                'slug' => 'orders-over-time',
                'description' => 'Track order volume by status over time',
                'category' => 'Orders',
                'type' => 'stacked_bar',
                'available_filters' => ['date_range' => ['today', 'yesterday', 'last_7_days', 'last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 1,
            ],
            [
                'name' => 'Orders by Status',
                'slug' => 'orders-by-status',
                'description' => 'Breakdown of completed, canceled, and refunded orders',
                'category' => 'Orders',
                'type' => 'pie_chart',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days']],
                'display_order' => 2,
            ],
            [
                'name' => 'Orders by Package Type',
                'slug' => 'orders-by-package-type',
                'description' => 'Ticket vs Table orders',
                'category' => 'Orders',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 3,
            ],
            [
                'name' => 'Multi-Package Orders',
                'slug' => 'multi-package-orders',
                'description' => 'Track orders with multiple packages',
                'category' => 'Orders',
                'type' => 'metric',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days']],
                'display_order' => 4,
            ],
            [
                'name' => 'Average Order Value',
                'slug' => 'average-order-value',
                'description' => 'Track AOV trends',
                'category' => 'Orders',
                'type' => 'metric',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 5,
            ],

            // ACQUISITION REPORTS
            [
                'name' => 'New affiliates Over Time',
                'slug' => 'new-affiliates-over-time',
                'description' => 'Track new affiliate signups',
                'category' => 'Acquisition',
                'type' => 'line_chart',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 1,
            ],
            [
                'name' => 'affiliate Performance Ranking',
                'slug' => 'affiliate-performance-ranking',
                'description' => 'Top performing affiliates by revenue',
                'category' => 'Acquisition',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 2,
            ],
            [
                'name' => 'affiliate Commission Tracking',
                'slug' => 'affiliate-commission-tracking',
                'description' => 'Commission owed to each affiliate',
                'category' => 'Acquisition',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 3,
            ],

            // ENTERTAINER REPORTS
            [
                'name' => 'Events Per Entertainer',
                'slug' => 'events-per-entertainer',
                'description' => 'Track events by entertainer',
                'category' => 'Entertainer',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 1,
            ],
            [
                'name' => 'Entertainer Earnings',
                'slug' => 'entertainer-earnings',
                'description' => 'Revenue and commission by entertainer',
                'category' => 'Entertainer',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 2,
            ],
            [
                'name' => 'Entertainer Commission Tracking',
                'slug' => 'entertainer-commission-tracking',
                'description' => 'Commission owed to entertainers',
                'category' => 'Entertainer',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 3,
            ],

            // PACKAGE REPORTS
            [
                'name' => 'Sales by Package',
                'slug' => 'sales-by-package',
                'description' => 'Orders and revenue by package',
                'category' => 'Product',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 1,
            ],
            [
                'name' => 'Most Popular Packages',
                'slug' => 'most-popular-packages',
                'description' => 'Top selling packages',
                'category' => 'Product',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 2,
            ],
            [
                'name' => 'Package Capacity Utilization',
                'slug' => 'package-capacity-utilization',
                'description' => 'Sold vs available capacity by package',
                'category' => 'Product',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 3,
            ],

            // CUSTOMER REPORTS
            [
                'name' => 'New Customers Over Time',
                'slug' => 'new-customers-over-time',
                'description' => 'Track new customer acquisition',
                'category' => 'Customers',
                'type' => 'line_chart',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 1,
            ],
            [
                'name' => 'Repeat vs First-Time Customers',
                'slug' => 'repeat-vs-first-time',
                'description' => 'Customer retention analysis',
                'category' => 'Customers',
                'type' => 'pie_chart',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 2,
            ],
            [
                'name' => 'Customers by Location',
                'slug' => 'customer-by-location',
                'description' => 'Geographic distribution of customers',
                'category' => 'Customers',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 3,
            ],

            // EVENT REPORTS
            [
                'name' => 'Attendance by Event',
                'slug' => 'attendance-by-event',
                'description' => 'Attendees and guests by event',
                'category' => 'Events',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 1,
            ],
            [
                'name' => 'Event Revenue',
                'slug' => 'event-revenue',
                'description' => 'Revenue generated by each event',
                'category' => 'Events',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 2,
            ],
            [
                'name' => 'Event Capacity Utilization',
                'slug' => 'event-capacity-utilization',
                'description' => 'Attendance vs capacity by event',
                'category' => 'Events',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month']],
                'display_order' => 3,
            ],

            // FINANCIAL REPORTS
            [
                'name' => 'Revenue Summary',
                'slug' => 'revenue-summary',
                'description' => 'Gross revenue and refund overview',
                'category' => 'Financial',
                'type' => 'metric',
                'available_filters' => ['date_range' => ['today', 'yesterday', 'last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 1,
            ],
            [
                'name' => 'Commission Expenses',
                'slug' => 'commission-expenses',
                'description' => 'Total commission paid to affiliates and entertainers',
                'category' => 'Financial',
                'type' => 'metric',
                'available_filters' => ['date_range' => ['last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 2,
            ],
            [
                'name' => 'Net Revenue',
                'slug' => 'net-revenue',
                'description' => 'Revenue after refunds and commissions',
                'category' => 'Financial',
                'type' => 'metric',
                'available_filters' => ['date_range' => ['today', 'yesterday', 'last_30_days', 'last_90_days', 'this_month', 'this_year']],
                'display_order' => 3,
            ],

            // TRAFFIC REPORTS
            [
                'name' => 'Sessions Over Time',
                'slug' => 'sessions-over-time',
                'description' => 'Track website sessions over time',
                'category' => 'Traffic',
                'type' => 'line_chart',
                'available_filters' => ['date_range' => ['today', 'yesterday', 'last_7_days', 'last_30_days', 'last_90_days', 'this_month', 'last_month', 'this_year', 'custom']],
                'display_order' => 1,
            ],
            [
                'name' => 'Visitors Over Time',
                'slug' => 'visitors-over-time',
                'description' => 'Track unique visitors over time',
                'category' => 'Traffic',
                'type' => 'line_chart',
                'available_filters' => ['date_range' => ['today', 'yesterday', 'last_7_days', 'last_30_days', 'last_90_days', 'this_month', 'last_month', 'this_year', 'custom']],
                'display_order' => 2,
            ],
            [
                'name' => 'Sessions by Referrer',
                'slug' => 'sessions-by-referrer',
                'description' => 'Top traffic referrers by session count',
                'category' => 'Traffic',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_7_days', 'last_30_days', 'last_90_days', 'this_month', 'last_month', 'custom']],
                'display_order' => 3,
            ],
            [
                'name' => 'Sessions by Landing Page',
                'slug' => 'sessions-by-landing-page',
                'description' => 'Top landing pages by session count',
                'category' => 'Traffic',
                'type' => 'table',
                'available_filters' => ['date_range' => ['last_7_days', 'last_30_days', 'last_90_days', 'this_month', 'last_month', 'custom']],
                'display_order' => 4,
            ],
        ];

        foreach ($reports as $reportData) {
            $report = Report::updateOrCreate(
                ['slug' => $reportData['slug']],
                $reportData
            );
            $this->line("✓ Created report: {$report->name}");
        }

        $this->info('Seeding report permissions...');

        // Set default permissions
        $this->seedPermissions();

        $this->info('Reports seeded successfully!');
    }

    private function seedPermissions()
    {
        // Admin can see all reports
        Report::each(function (Report $report) {
            ReportPermission::updateOrCreate(
                [
                    'report_id' => $report->id,
                    'user_type' => 'admin',
                ],
                []
            );
        });

        // Website staff (bouncer, manager) see sales, orders, customer, event reports
        $websiteStaffReports = ['Sales', 'Orders', 'Product', 'Customers', 'Events', 'Traffic'];
        Report::whereIn('category', $websiteStaffReports)->each(function (Report $report) {
            foreach (['bouncer', 'manager'] as $userType) {
                ReportPermission::updateOrCreate(
                    [
                        'report_id' => $report->id,
                        'user_type' => $userType,
                    ],
                    []
                );
            }
        });

        // affiliates see acquisition reports (their own)
        $acquisitionReports = Report::where('category', 'Acquisition')->pluck('id');
        foreach ($acquisitionReports as $reportId) {
            ReportPermission::updateOrCreate(
                [
                    'report_id' => $reportId,
                    'user_type' => 'affiliate',
                ],
                []
            );
        }

        // Entertainers see entertainer reports
        $entertainerReports = Report::where('category', 'Entertainer')->pluck('id');
        foreach ($entertainerReports as $reportId) {
            ReportPermission::updateOrCreate(
                [
                    'report_id' => $reportId,
                    'user_type' => 'entertainer',
                ],
                []
            );
        }

        $this->info('Report permissions seeded');
    }
}
