@extends('admin.main')

@section('title', 'Sub-Promoter Management')

@section('content')
<style>
    .sub-card-dark {
        background-color: #1b1b29 !important;
        border: 1px solid rgba(255, 255, 255, 0.12) !important;
        border-radius: 14px !important;
    }
    .modal-content-dark {
        background-color: #1b1b29 !important;
        border: 1px solid rgba(255, 255, 255, 0.12) !important;
        border-radius: 14px !important;
        box-shadow: 0 20px 50px rgba(0, 0, 0, 0.6) !important;
    }
    .text-white-title {
        color: #ffffff !important;
        font-weight: 700 !important;
    }
    .text-muted-sub {
        color: #cbd5e1 !important;
    }
    .alloc-box {
        background: rgba(255, 255, 255, 0.04) !important;
        border: 1px solid rgba(255, 255, 255, 0.12) !important;
        border-radius: 8px !important;
        max-height: 220px;
        overflow-y: auto;
        padding: 14px;
    }
    /* Sleek Custom CartVIP Switch */
    .cartvip-switch {
        position: relative;
        display: inline-block;
        width: 48px;
        height: 26px;
        flex-shrink: 0;
    }
    .cartvip-switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }
    .cartvip-slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #334155;
        transition: .3s ease;
        border-radius: 26px;
        border: 1px solid rgba(255, 255, 255, 0.2);
    }
    .cartvip-slider:before {
        position: absolute;
        content: "";
        height: 18px;
        width: 18px;
        left: 3px;
        bottom: 3px;
        background-color: #ffffff;
        transition: .3s ease;
        border-radius: 50%;
        box-shadow: 0 2px 4px rgba(0,0,0,0.3);
    }
    .cartvip-switch input:checked + .cartvip-slider {
        background-color: #4f46e5;
        border-color: #6366f1;
    }
    .cartvip-switch input:checked + .cartvip-slider:before {
        transform: translateX(22px);
    }
</style>

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3">
        <div>
            <h4 class="fw-bold py-1 mb-1 text-white-title">
                <span class="text-muted fw-light">Portal /</span> Sub-Promoter Management
            </h4>
            <p class="text-muted-sub mb-0">Create and manage sub-promoters under your team. All sales commissions generated by your sub-promoters automatically accrue to your primary wallet.</p>
        </div>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createSubAffiliateModal">
            <i class="bx bx-user-plus me-1"></i> Add Sub-Promoter
        </button>
    </div>

    @if(session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="bx bx-check-circle me-1"></i> {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    @if(session('error'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <i class="bx bx-error me-1"></i> {{ session('error') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif

    <div class="card sub-card-dark shadow-sm">
        <div class="card-header border-bottom border-secondary d-flex justify-content-between align-items-center py-3">
            <h5 class="card-title mb-0 text-white-title">
                <i class="bx bx-group text-primary me-2"></i> My Sub-Promoters ({{ $subAffiliates->count() }})
            </h5>
        </div>
        <div class="card-body py-3">
            @if($subAffiliates->count() === 0)
                <div class="text-center py-5">
                    <div class="avatar avatar-xl bg-label-primary rounded-circle mx-auto mb-3 d-flex align-items-center justify-content-center">
                        <i class="bx bx-user-plus fs-1"></i>
                    </div>
                    <h5 class="text-white-title mb-2">No Sub-Promoters Added Yet</h5>
                    <p class="text-muted-sub max-w-md mx-auto mb-4">Expand your reach by creating sub-promoter accounts. Allocate clubs and custom dashboard access permissions.</p>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createSubAffiliateModal">
                        <i class="bx bx-user-plus me-1"></i> Create First Sub-Promoter
                    </button>
                </div>
            @else
                <div class="table-responsive text-nowrap">
                    <table class="table table-hover align-middle">
                        <thead>
                            <tr>
                                <th class="text-white">Sub-Promoter Name</th>
                                <th class="text-white">Email & Login</th>
                                <th class="text-white">Public Link</th>
                                <th class="text-white">Allocated Clubs</th>
                                <th class="text-white">Status</th>
                                <th class="text-white text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($subAffiliates as $sub)
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center gap-2">
                                            <div class="avatar avatar-sm bg-label-info rounded-circle d-flex align-items-center justify-content-center">
                                                <i class="bx bx-user fs-6"></i>
                                            </div>
                                            <div>
                                                <h6 class="mb-0 text-white-title fs-7">{{ $sub->display_name ?: $sub->user->name }}</h6>
                                                <small class="text-muted fs-8">Added {{ $sub->created_at->format('M d, Y') }}</small>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="text-white fs-7">{{ $sub->user->email }}</span>
                                    </td>
                                    <td>
                                        <a href="{{ route('affiliate.public', $sub->slug) }}" target="_blank" class="text-primary fs-7 text-decoration-none">
                                            <i class="bx bx-external-link me-1"></i> /affiliate/{{ $sub->slug }}
                                        </a>
                                    </td>
                                    <td>
                                        <span class="badge bg-label-primary">{{ $sub->affiliateWebsites->count() }} Clubs Allocated</span>
                                    </td>
                                    <td>
                                        @if(!$sub->is_active)
                                            <span class="badge bg-danger">Disabled</span>
                                        @elseif($sub->status === 'approved')
                                            <span class="badge bg-success">Active</span>
                                        @else
                                            <span class="badge bg-warning">Pending Onboarding Form</span>
                                        @endif
                                    </td>
                                    <td class="text-end">
                                        <div class="d-flex align-items-center justify-content-end gap-2">
                                            <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#editSubAffiliateModal-{{ $sub->id }}">
                                                <i class="bx bx-pencil me-1"></i> Edit
                                            </button>
                                            <form action="{{ route('affiliate.portal.sub-affiliates.toggle-status', $sub->id) }}" method="POST" class="d-inline">
                                                @csrf
                                                <button type="submit" class="btn btn-sm {{ $sub->is_active ? 'btn-outline-danger' : 'btn-outline-success' }}">
                                                    {{ $sub->is_active ? 'Disable' : 'Enable' }}
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endif
        </div>
    </div>
</div>

<!-- CREATE SUB-PROMOTER MODAL -->
<div class="modal fade" id="createSubAffiliateModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <form action="{{ route('affiliate.portal.sub-affiliates.store') }}" method="POST" class="modal-content modal-content-dark">
            @csrf
            <div class="modal-header border-bottom border-secondary pb-3">
                <h5 class="modal-title text-white-title">Add New Sub-Promoter</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body py-4">
                <div class="row g-3 mb-4">
                    <div class="col-md-6">
                        <label class="form-label text-white">Full Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" class="form-control" placeholder="e.g., Alex Johnson" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label text-white font-weight-bold d-flex align-items-center justify-content-between">
                            <span>Display Name <span class="text-danger">*</span></span>
                            <span class="badge bg-warning text-dark fs-8"><i class="bx bx-star me-1"></i> Public Title & URL</span>
                        </label>
                        <input type="text" name="display_name" class="form-control border-warning shadow-sm" placeholder="e.g., Alex VIP Events" required>
                        <small class="text-warning fs-8 d-block mt-1"><i class="bx bx-info-circle me-1"></i> This name appears on the public landing page & URL.</small>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label text-white">Email Address <span class="text-danger">*</span></label>
                        <input type="email" name="email" class="form-control" placeholder="alex@example.com" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label text-white">Initial Password <span class="text-danger">*</span></label>
                        <input type="password" name="password" class="form-control" placeholder="At least 6 characters" minlength="6" required>
                    </div>
                </div>

                <hr class="border-secondary my-4">

                <!-- ALLOCATE CLUBS / WEBSITES -->
                <h6 class="text-white-title mb-2"><i class="bx bx-building-house me-1 text-primary"></i> Allocate Clubs / Websites</h6>
                <p class="text-muted-sub fs-7 mb-3">Sub-promoters can only access packages from the clubs allocated below.</p>

                <div class="mb-4">
                    <div class="alloc-box">
                        @foreach($websites as $web)
                            <div class="form-check mb-2">
                                <input type="checkbox" name="website_ids[]" value="{{ $web->id }}" id="create_web_{{ $web->id }}" class="form-check-input" checked>
                                <label class="form-check-label text-white fs-7" for="create_web_{{ $web->id }}">{{ $web->name }}</label>
                            </div>
                        @endforeach
                    </div>
                </div>

                <hr class="border-secondary my-4">

                <!-- ONBOARDING & DASHBOARD TOGGLES -->
                <h6 class="text-white-title mb-3"><i class="bx bx-slider-alt me-1 text-primary"></i> Onboarding Rules & Dashboard Toggles</h6>

                <!-- Require Extra Onboarding Form Toggle -->
                <div class="p-3 bg-dark rounded border border-secondary mb-3 d-flex align-items-center justify-content-between">
                    <div>
                        <h6 class="mb-0 text-white font-weight-bold">Require Extra Onboarding Form Before Activation</h6>
                        <small class="text-muted-sub">If enabled, an email with a form link is sent. Status remains pending until form is submitted.</small>
                    </div>
                    <label class="cartvip-switch mb-0">
                        <input type="checkbox" name="require_onboarding_form" value="1">
                        <span class="cartvip-slider"></span>
                    </label>
                </div>

                <!-- Dashboard Feature Visibility Toggles -->
                <div class="row g-3">
                    <div class="col-md-6">
                        <div class="p-3 bg-dark rounded border border-secondary d-flex align-items-center justify-content-between">
                            <div>
                                <h6 class="mb-0 text-white fs-7">Show Packages Tab</h6>
                                <small class="text-muted-sub fs-8">Allow sub-promoter to view packages.</small>
                            </div>
                            <label class="cartvip-switch mb-0">
                                <input type="checkbox" name="show_packages" value="1" checked>
                                <span class="cartvip-slider"></span>
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="p-3 bg-dark rounded border border-secondary d-flex align-items-center justify-content-between">
                            <div>
                                <h6 class="mb-0 text-white fs-7">Show Page Customization Tab</h6>
                                <small class="text-muted-sub fs-8">Allow editing bio, photos, and branding.</small>
                            </div>
                            <label class="cartvip-switch mb-0">
                                <input type="checkbox" name="show_settings" value="1" checked>
                                <span class="cartvip-slider"></span>
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="p-3 bg-dark rounded border border-secondary d-flex align-items-center justify-content-between">
                            <div>
                                <h6 class="mb-0 text-white fs-7">Show QR Code & Share Link</h6>
                                <small class="text-muted-sub fs-8">Display shareable public page link & QR code.</small>
                            </div>
                            <label class="cartvip-switch mb-0">
                                <input type="checkbox" name="show_qr_code" value="1" checked>
                                <span class="cartvip-slider"></span>
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="p-3 bg-dark rounded border border-secondary d-flex align-items-center justify-content-between">
                            <div>
                                <h6 class="mb-0 text-white fs-7">Show Sales Statistics</h6>
                                <small class="text-muted-sub fs-8">Display booking counts and gross sales stats.</small>
                            </div>
                            <label class="cartvip-switch mb-0">
                                <input type="checkbox" name="show_sales_stats" value="1" checked>
                                <span class="cartvip-slider"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer border-top border-secondary pt-3">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Create Sub-Promoter Account</button>
            </div>
        </form>
    </div>
</div>

@foreach($subAffiliates as $sub)
<!-- EDIT SUB-PROMOTER MODAL -->
<div class="modal fade" id="editSubAffiliateModal-{{ $sub->id }}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <form action="{{ route('affiliate.portal.sub-affiliates.update', $sub->id) }}" method="POST" class="modal-content modal-content-dark">
            @csrf
            @method('PUT')
            <div class="modal-header border-bottom border-secondary pb-3">
                <h5 class="modal-title text-white-title">Edit Sub-Promoter: {{ $sub->display_name ?: $sub->user->name }}</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body py-4">
                <div class="row g-3 mb-4">
                    <div class="col-md-6">
                        <label class="form-label text-white font-weight-bold d-flex align-items-center justify-content-between">
                            <span>Display Name <span class="text-danger">*</span></span>
                            <span class="badge bg-warning text-dark fs-8"><i class="bx bx-star me-1"></i> Public Title & URL</span>
                        </label>
                        <input type="text" name="display_name" class="form-control border-warning shadow-sm" value="{{ $sub->display_name }}" required>
                        <small class="text-warning fs-8 d-block mt-1"><i class="bx bx-info-circle me-1"></i> This name appears on the public landing page & URL.</small>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label text-white">Email Address</label>
                        <input type="email" class="form-control" value="{{ $sub->user->email }}" readonly disabled>
                    </div>
                </div>

                <hr class="border-secondary my-4">

                <!-- ALLOCATE CLUBS / WEBSITES -->
                <h6 class="text-white-title mb-2"><i class="bx bx-building-house me-1 text-primary"></i> Allocated Clubs / Websites</h6>
                @php
                    $subWebIds = $sub->affiliateWebsites->pluck('website_id')->toArray();
                @endphp
                <div class="mb-4">
                    <div class="alloc-box">
                        @foreach($websites as $web)
                            <div class="form-check mb-2">
                                <input type="checkbox" name="website_ids[]" value="{{ $web->id }}" id="edit_web_{{ $sub->id }}_{{ $web->id }}" class="form-check-input" {{ in_array($web->id, $subWebIds) ? 'checked' : '' }}>
                                <label class="form-check-label text-white fs-7" for="edit_web_{{ $sub->id }}_{{ $web->id }}">{{ $web->name }}</label>
                            </div>
                        @endforeach
                    </div>
                </div>

                <hr class="border-secondary my-4">

                <!-- ONBOARDING & DASHBOARD TOGGLES -->
                <h6 class="text-white-title mb-3"><i class="bx bx-slider-alt me-1 text-primary"></i> Onboarding Rules & Dashboard Toggles</h6>

                <!-- Require Extra Onboarding Form Toggle -->
                <div class="p-3 bg-dark rounded border border-secondary mb-3 d-flex align-items-center justify-content-between">
                    <div>
                        <h6 class="mb-0 text-white font-weight-bold">Require Extra Onboarding Form Before Activation</h6>
                        <small class="text-muted-sub">If enabled, an email with a form link is sent.</small>
                    </div>
                    <label class="cartvip-switch mb-0">
                        <input type="checkbox" name="require_onboarding_form" value="1" {{ $sub->require_onboarding_form ? 'checked' : '' }}>
                        <span class="cartvip-slider"></span>
                    </label>
                </div>

                <!-- Dashboard Feature Visibility Toggles -->
                <div class="row g-3">
                    <div class="col-md-6">
                        <div class="p-3 bg-dark rounded border border-secondary d-flex align-items-center justify-content-between">
                            <div>
                                <h6 class="mb-0 text-white fs-7">Show Packages Tab</h6>
                            </div>
                            <label class="cartvip-switch mb-0">
                                <input type="checkbox" name="show_packages" value="1" {{ $sub->hasSubPermission('show_packages') ? 'checked' : '' }}>
                                <span class="cartvip-slider"></span>
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="p-3 bg-dark rounded border border-secondary d-flex align-items-center justify-content-between">
                            <div>
                                <h6 class="mb-0 text-white fs-7">Show Page Customization Tab</h6>
                            </div>
                            <label class="cartvip-switch mb-0">
                                <input type="checkbox" name="show_settings" value="1" {{ $sub->hasSubPermission('show_settings') ? 'checked' : '' }}>
                                <span class="cartvip-slider"></span>
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="p-3 bg-dark rounded border border-secondary d-flex align-items-center justify-content-between">
                            <div>
                                <h6 class="mb-0 text-white fs-7">Show QR Code & Share Link</h6>
                            </div>
                            <label class="cartvip-switch mb-0">
                                <input type="checkbox" name="show_qr_code" value="1" {{ $sub->hasSubPermission('show_qr_code') ? 'checked' : '' }}>
                                <span class="cartvip-slider"></span>
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="p-3 bg-dark rounded border border-secondary d-flex align-items-center justify-content-between">
                            <div>
                                <h6 class="mb-0 text-white fs-7">Show Sales Statistics</h6>
                            </div>
                            <label class="cartvip-switch mb-0">
                                <input type="checkbox" name="show_sales_stats" value="1" {{ $sub->hasSubPermission('show_sales_stats') ? 'checked' : '' }}>
                                <span class="cartvip-slider"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer border-top border-secondary pt-3">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Save Changes</button>
            </div>
        </form>
    </div>
</div>
@endforeach
@endsection
